#!/bin/bash
# ./check_ram_snmp <community> <IP> <warn> <crit>

var=`snmpget -v2c -c $1 $2 .1.3.6.1.4.1.2636.3.1.13.1.11.9.1.0.0 -O vq`
echo " Used Memory : $var %"

if [ $var -ge $3 ]		# Warning
	then
	if [ $var -ge $4 ]	# Critical
		then
		exit 2
	fi
	exit 1
fi
