#!/bin/bash
# ./check_load_snmp <community> <IP> <warn> <crit>

#Charges sur 1min, 5min, 15min
L1=`snmpget -v2c -c $1 $2 .1.3.6.1.4.1.2636.3.1.13.1.20.9.1.0.0 -O vq`
L5=`snmpget -v2c -c $1 $2 .1.3.6.1.4.1.2636.3.1.13.1.21.9.1.0.0 -O vq`
L15=`snmpget -v2c -c $1 $2 .1.3.6.1.4.1.2636.3.1.13.1.22.9.1.0.0 -O vq`

var=0
L1=`bc <<< "scale=2; $L1/100"`
L1="$var$L1"

L5=`bc <<< "scale=2; $L5/100"`
L5="$var$L5"

L15=`bc <<< "scale=2; $L15/100"`
L15="$var$L15"




echo " Load : $L1 %, $L5 %, $L15 %"

if (( $(echo "$L1 > $3" | bc -l) ));           # Warning
        then
        if (( $(echo "$L1 > $4" | bc -l) ));   # Critical
                then
                exit 2
        fi
        exit 1
fi

