#!/bin/bash
# ./check_failover_snmp_juniper <community> <IP> <warn> <crit>

count1=`snmpget -v2c -c $1 $2 .1.3.6.1.4.1.2636.3.1.14.1.8.9.1.0.0 -O vq`
count2=`snmpget -v2c -c $1 $2 .1.3.6.1.4.1.2636.3.1.14.1.8.9.2.0.0 -O vq`
reason1=`snmpget -v2c -c $1 $2 .1.3.6.1.4.1.2636.3.1.14.1.10.9.1.0.0 -O vq`
reason2=`snmpget -v2c -c $1 $2 .1.3.6.1.4.1.2636.3.1.14.1.10.9.1.0.0 -O vq`

if [ $reason1 -eq 0 ];                                    #
        then                                              #
                reason1="Other"                           #
        elif [ $reason1 -eq 1 ];                          #
                then                                      #
                        reason1="Never Switched"          # Raison du failover
        elif [ $reason1 -eq 2 ];                          # Pour le Master
                then                                      #
                        reason1="User Switched"           #
        else reason1="Auto Switched"                      #
fi                                                        #

if [ $reason2 -eq 0 ];                                    #
        then                                              #
                reason2="Other"                           #
        elif [ $reason2 -eq 1 ];                          #
                then                                      #
                        reason2="Never Switched"          # Raison du failover
        elif [ $reason2 -eq 2 ];                          # Pour le Slave
                then                                      #
                        reason2="User Switched"           #
        else reason2="Auto Switched"                      #
fi           

echo "Master : failovers : $count1, reason : $reason1  /  Slave  : failovers : $count2, reason : $reason2"

if (( $(echo "$count1 > $3" | bc -l) ));
	then
	if (( $(echo "$count1 > $4" | bc -l) ));
		then
		exit 2
	fi
	exit 1
fi


