#!/bin/bash
# ./check_radio_snmp_aerohive <community> <IP> <warn> <crit>

# Number of transmit data frames
var=`snmpget -v2c -c $1 $2 .1.3.6.1.4.1.26928.1.1.1.2.1.3.1.1.5 -O vq`		# Reset every 30 sec
var2=`snmpget -v2c -c $1 $2 .1.3.6.1.4.1.26928.1.1.1.2.1.3.1.1.6 -O vq` 	# Reset every 30 sec
var3=$(($var+$var2))

# Number of frames dropped
var4=`snmpget -v2c -c $1 $2 .1.3.6.1.4.1.26928.1.1.1.2.1.3.1.8.5 -O vq`          # Reset every 30 sec
var5=`snmpget -v2c -c $1 $2 .1.3.6.1.4.1.26928.1.1.1.2.1.3.1.8.6 -O vq`          # Reset every 30 sec
var6=$(($var4+$var5))

# Ratio dropped/transmit
var7=`echo "scale = 3; ($var6 / $var3)*100" | bc`
var7=$((var7*1))

echo " Frames lost : ${var7}% | Transmit : $var3, Dropped : $var6"

if (( $(echo "$var7 > $3" | bc -l) ));
	then
	if (( $(echo "$var7 > $4" | bc -l) ));
		then
		exit 2
	fi
	exit 1
fi
