#!/bin/bash
# ./check_load_snmp <community> <IP> <warn> <crit>

#Charges sur 1min, 5min, 15min
L1=`snmpget -v2c -c $1 $2 .1.3.6.1.4.1.2636.3.1.13.1.20.9.1.0.0 -O vq`
L5=`snmpget -v2c -c $1 $2 .1.3.6.1.4.1.2636.3.1.13.1.21.9.1.0.0 -O vq`
L15=`snmpget -v2c -c $1 $2 .1.3.6.1.4.1.2636.3.1.13.1.22.9.1.0.0 -O vq`

echo " Load : $L1 %, $L5 %, $L15 %"

if [ $L5 -ge $3 ]		# Warning
	then
	if [ $L5 -ge $4 ]	# Critical
		then
		exit 2
	fi
	exit 1
fi
