#!/bin/bash
# ./check_cpu_snmp <community> <IP> <warn> <crit>
var=`snmpget -v2c -c $1 $2 .1.3.6.1.4.1.2636.3.1.13.1.8.9.1.0.0 -O vq`
var=`bc <<< "scale=2; $var/100"`
var2=0
var="$var2$var"

echo " CPU Load : $var %"

if (( $(echo "$var > $3" | bc -l) ));		# Warning
	then
	if (( $(echo "$var > $4" | bc -l) ));	# Critical
		then
		exit 2
	fi
	exit 1
fi

